// Country reference used by the flag dropdowns on the Contact form (and anywhere
// else a country / dialing-code picker is needed).
//
// `iso` is the lowercase ISO-3166 alpha-2 code — it doubles as the flag lookup
// on flagcdn.com (https://flagcdn.com/<iso>.svg), which is why we render real
// flag images instead of emoji: Windows has no flag-emoji glyphs and would show
// bare letter pairs ("IN") instead of a flag.

export interface Country {
  name: string;
  iso: string;  // lowercase alpha-2, e.g. "in"
  dial: string; // e.g. "+91"
}

/** Flag image URL for an ISO alpha-2 code (SVG scales crisply at any size). */
export const flagUrl = (iso: string) => `https://flagcdn.com/${iso}.svg`;

// Broad, real-world list. Sourcing-relevant markets (India, China, UAE,
// Singapore, Malaysia, UK, US…) are all present, plus wide global coverage.
export const COUNTRIES: Country[] = [
  { name: "India", iso: "in", dial: "+91" },
  { name: "China", iso: "cn", dial: "+86" },
  { name: "United States", iso: "us", dial: "+1" },
  { name: "United Kingdom", iso: "gb", dial: "+44" },
  { name: "United Arab Emirates", iso: "ae", dial: "+971" },
  { name: "Singapore", iso: "sg", dial: "+65" },
  { name: "Malaysia", iso: "my", dial: "+60" },
  { name: "Saudi Arabia", iso: "sa", dial: "+966" },
  { name: "Qatar", iso: "qa", dial: "+974" },
  { name: "Kuwait", iso: "kw", dial: "+965" },
  { name: "Bahrain", iso: "bh", dial: "+973" },
  { name: "Oman", iso: "om", dial: "+968" },
  { name: "Australia", iso: "au", dial: "+61" },
  { name: "Canada", iso: "ca", dial: "+1" },
  { name: "Germany", iso: "de", dial: "+49" },
  { name: "France", iso: "fr", dial: "+33" },
  { name: "Italy", iso: "it", dial: "+39" },
  { name: "Spain", iso: "es", dial: "+34" },
  { name: "Netherlands", iso: "nl", dial: "+31" },
  { name: "Belgium", iso: "be", dial: "+32" },
  { name: "Switzerland", iso: "ch", dial: "+41" },
  { name: "Sweden", iso: "se", dial: "+46" },
  { name: "Norway", iso: "no", dial: "+47" },
  { name: "Denmark", iso: "dk", dial: "+45" },
  { name: "Finland", iso: "fi", dial: "+358" },
  { name: "Ireland", iso: "ie", dial: "+353" },
  { name: "Portugal", iso: "pt", dial: "+351" },
  { name: "Austria", iso: "at", dial: "+43" },
  { name: "Poland", iso: "pl", dial: "+48" },
  { name: "Czechia", iso: "cz", dial: "+420" },
  { name: "Greece", iso: "gr", dial: "+30" },
  { name: "Turkey", iso: "tr", dial: "+90" },
  { name: "Russia", iso: "ru", dial: "+7" },
  { name: "Ukraine", iso: "ua", dial: "+380" },
  { name: "Romania", iso: "ro", dial: "+40" },
  { name: "Hungary", iso: "hu", dial: "+36" },
  { name: "Japan", iso: "jp", dial: "+81" },
  { name: "South Korea", iso: "kr", dial: "+82" },
  { name: "Hong Kong", iso: "hk", dial: "+852" },
  { name: "Taiwan", iso: "tw", dial: "+886" },
  { name: "Thailand", iso: "th", dial: "+66" },
  { name: "Vietnam", iso: "vn", dial: "+84" },
  { name: "Indonesia", iso: "id", dial: "+62" },
  { name: "Philippines", iso: "ph", dial: "+63" },
  { name: "Bangladesh", iso: "bd", dial: "+880" },
  { name: "Pakistan", iso: "pk", dial: "+92" },
  { name: "Sri Lanka", iso: "lk", dial: "+94" },
  { name: "Nepal", iso: "np", dial: "+977" },
  { name: "Cambodia", iso: "kh", dial: "+855" },
  { name: "Myanmar", iso: "mm", dial: "+95" },
  { name: "New Zealand", iso: "nz", dial: "+64" },
  { name: "South Africa", iso: "za", dial: "+27" },
  { name: "Nigeria", iso: "ng", dial: "+234" },
  { name: "Kenya", iso: "ke", dial: "+254" },
  { name: "Egypt", iso: "eg", dial: "+20" },
  { name: "Morocco", iso: "ma", dial: "+212" },
  { name: "Ghana", iso: "gh", dial: "+233" },
  { name: "Tanzania", iso: "tz", dial: "+255" },
  { name: "Ethiopia", iso: "et", dial: "+251" },
  { name: "Israel", iso: "il", dial: "+972" },
  { name: "Jordan", iso: "jo", dial: "+962" },
  { name: "Lebanon", iso: "lb", dial: "+961" },
  { name: "Iraq", iso: "iq", dial: "+964" },
  { name: "Iran", iso: "ir", dial: "+98" },
  { name: "Brazil", iso: "br", dial: "+55" },
  { name: "Mexico", iso: "mx", dial: "+52" },
  { name: "Argentina", iso: "ar", dial: "+54" },
  { name: "Chile", iso: "cl", dial: "+56" },
  { name: "Colombia", iso: "co", dial: "+57" },
  { name: "Peru", iso: "pe", dial: "+51" },
  { name: "Ecuador", iso: "ec", dial: "+593" },
  { name: "Venezuela", iso: "ve", dial: "+58" },
  { name: "Bolivia", iso: "bo", dial: "+591" },
  { name: "Uruguay", iso: "uy", dial: "+598" },
  { name: "Paraguay", iso: "py", dial: "+595" },
  { name: "Bulgaria", iso: "bg", dial: "+359" },
  { name: "Croatia", iso: "hr", dial: "+385" },
  { name: "Serbia", iso: "rs", dial: "+381" },
  { name: "Slovakia", iso: "sk", dial: "+421" },
  { name: "Slovenia", iso: "si", dial: "+386" },
  { name: "Lithuania", iso: "lt", dial: "+370" },
  { name: "Latvia", iso: "lv", dial: "+371" },
  { name: "Estonia", iso: "ee", dial: "+372" },
  { name: "Iceland", iso: "is", dial: "+354" },
  { name: "Luxembourg", iso: "lu", dial: "+352" },
  { name: "Kazakhstan", iso: "kz", dial: "+7" },
  { name: "Uzbekistan", iso: "uz", dial: "+998" },
  { name: "Azerbaijan", iso: "az", dial: "+994" },
  { name: "Georgia", iso: "ge", dial: "+995" },
  { name: "Armenia", iso: "am", dial: "+374" },
  { name: "Afghanistan", iso: "af", dial: "+93" },
  { name: "Maldives", iso: "mv", dial: "+960" },
  { name: "Mauritius", iso: "mu", dial: "+230" },
  { name: "Fiji", iso: "fj", dial: "+679" },
  { name: "Yemen", iso: "ye", dial: "+967" },
  { name: "Syria", iso: "sy", dial: "+963" },
  { name: "Algeria", iso: "dz", dial: "+213" },
  { name: "Tunisia", iso: "tn", dial: "+216" },
  { name: "Libya", iso: "ly", dial: "+218" },
  { name: "Sudan", iso: "sd", dial: "+249" },
  { name: "Uganda", iso: "ug", dial: "+256" },
  { name: "Zimbabwe", iso: "zw", dial: "+263" },
  { name: "Zambia", iso: "zm", dial: "+260" },
  { name: "Angola", iso: "ao", dial: "+244" },
  { name: "Senegal", iso: "sn", dial: "+221" },
  { name: "Ivory Coast", iso: "ci", dial: "+225" },
  { name: "Cameroon", iso: "cm", dial: "+237" },
];
