// GENERATED by scripts/build_ship_assets.mjs — do not edit by hand.
//
// Cut from public/affhan-ship.png (1697x927; artwork 875x870
// at 393,54). After replacing that image, re-run the script: it rewrites
// both files and these numbers together, so a declared width/height can never
// disagree with the file it describes.

export const SHIP_MARK_NAV = { src: "/affhan-ship-nav.webp", width: 96, height: 95 } as const;
export const SHIP_MARK_HERO = { src: "/affhan-ship-hero.webp", width: 480, height: 477 } as const;
