// Cut the drawn ship-mark files from the one source image, and record their
// real dimensions where the components read them.
//
//   node scripts/build_ship_assets.mjs
//
// Run it after replacing public/affhan-ship.png. That source is never served
// itself — at 1697x927 and ~0.5 MB, most of it transparent canvas, it is the
// wrong file for every place the mark appears. From it this writes:
//
//   public/affhan-ship-nav.webp   the homepage "Affhan Shipping" pill (40px)
//   public/affhan-ship-hero.webp  the /shipping/ hero (up to 260px)
//   src/lib/shipMarkAssets.ts     src + width + height for both
//
// Why a generated module: next.config sets images.unoptimized, so each file
// ships exactly as it sits in /public, and the width/height a component
// declares is the only thing that tells the browser the aspect ratio before
// the image arrives. Every earlier logo swap needed those numbers re-typed in
// several files by hand, and a stale pair is how the hero came to declare
// 1200x448 for a mark that had become square. Reading them from here, written
// from the files as actually encoded, makes that mismatch impossible.
//
// Trimming is by alpha, not by sharp's trim(): trim() keys off the top-left
// pixel, which is correct for a transparent canvas today and silently wrong the
// first time a replacement arrives with a painted corner.

import fs from "node:fs";
import sharp from "sharp";

const SRC = "public/affhan-ship.png";
const MODULE = "src/lib/shipMarkAssets.ts";

// Pixels at or below this alpha are treated as empty when finding the art's
// edges — the source carries a few near-invisible specks well outside the mark.
const ALPHA_EMPTY = 4;
// Kept around the art so the anti-aliased rim is never shaved off.
const PAD = 2;

const TARGETS = [
  {
    name: "SHIP_MARK_NAV",
    file: "public/affhan-ship-nav.webp",
    // Drawn 40px tall, so 96 covers a 2.4x screen. Lossy on purpose: the
    // mark is fine lines over a gradient, which lossless encodes at 18 KB
    // against 7.8 KB here — and this file sits in the homepage's first paint,
    // where image weight is what the LCP is made of.
    longSide: 96,
    webp: { quality: 92, alphaQuality: 100 },
  },
  {
    name: "SHIP_MARK_HERO",
    file: "public/affhan-ship-hero.webp",
    // Drawn at most 260px wide; 480 is close to 2x of that. q82 puts it at
    // ~66 KB, where the 1697x927 source it replaces was 517 KB.
    longSide: 480,
    webp: { quality: 82, alphaQuality: 90 },
  },
];

const { data, info } = await sharp(SRC).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
let x0 = Infinity, y0 = Infinity, x1 = -1, y1 = -1;
for (let y = 0; y < info.height; y++) {
  for (let x = 0; x < info.width; x++) {
    if (data[(y * info.width + x) * info.channels + 3] > ALPHA_EMPTY) {
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }
}
if (x1 < 0) throw new Error(`${SRC} has no visible pixels`);

const left = Math.max(0, x0 - PAD);
const top = Math.max(0, y0 - PAD);
const width = Math.min(info.width, x1 + 1 + PAD) - left;
const height = Math.min(info.height, y1 + 1 + PAD) - top;
const art = await sharp(SRC).extract({ left, top, width, height }).png().toBuffer();

console.log(`${SRC}: ${info.width}x${info.height}, artwork ${width}x${height} at (${left}, ${top})`);

const written = [];
for (const t of TARGETS) {
  await sharp(art)
    .resize(t.longSide, t.longSide, { fit: "inside" })
    .webp({ ...t.webp, effort: 6 })
    .toFile(t.file);
  // Declare what was actually encoded, not what was asked for.
  const m = await sharp(t.file).metadata();
  const bytes = fs.statSync(t.file).size;
  written.push({ ...t, width: m.width, height: m.height });
  console.log(`  ${t.file.padEnd(30)} ${m.width}x${m.height}  ${(bytes / 1024).toFixed(1)} KB`);
}

const src = (file) => file.replace(/^public/, "");
fs.writeFileSync(
  MODULE,
  `// GENERATED by scripts/build_ship_assets.mjs — do not edit by hand.
//
// Cut from public/affhan-ship.png (${info.width}x${info.height}; artwork ${width}x${height}
// at ${left},${top}). After replacing that image, re-run the script: it rewrites
// both files and these numbers together, so a declared width/height can never
// disagree with the file it describes.

${written
  .map((t) => `export const ${t.name} = { src: "${src(t.file)}", width: ${t.width}, height: ${t.height} } as const;`)
  .join("\n")}
`
);
console.log(`  ${MODULE}`);
